### ISSUE TITLE
Unknown symbol in Scale2DSystem

### ISSUE THREAD

**Issue by MilanDierick** [Necromantic/ECS-Sandbox#1]
Heya,
I cloned your repo, and everything is looking fantastic, the only issue I'm having is that I got an unknown symbol in Scale2DSystem at line 39. Do I need to add another dependency, or how should I go about solving this?

**Comment by Necromantic** [comment]
Which Unity version are you using?
That line contains operations from the new math library maybe that is missing for you?

**Comment by MilanDierick** [comment]
I'm sitting at Unity 2018.2.0f2, so it should be the latest version...

**Comment by MilanDierick** [comment]
What version did you use when building this?

**Comment by Necromantic** [comment]
Unity 2018.1.2 with some Preview Packages. There must be a problem with the upgrade to newer features or now built-in features that were experimental before. I'll see what I can do about it.

**Comment by MilanDierick** [comment]
I think that I got your version still installed, I'll launch that one and see if I can pull the required packages.

**Comment by MilanDierick** [comment]
I can't solve the problem by downgrading, and I don't seem to be finding the preview packages you're talking about. Could you list the math package that you used for this project? I can try and force Unity to download the correct package.

**Comment by Necromantic** [comment]
It should all really be included, did you revert all changes before switching back to the older version? Since Unity does change the project when you open it with a newer version.
I'll look into upgrading the project anyway.

**Comment by MilanDierick** [comment]
I'll clone your project again and open it with the downgraded version of Unity right away.

**Comment by MilanDierick** [comment]
Opening a fresh clone with the older version of Unity does the trick...
Since you said that you will be taking a look at updating the project to the latest update, I think I'll keep using the latest version of Unity and keep the scaling at 1, I don't really need scaling at the moment.

**Comment by MilanDierick** [comment]
I have attached my manifest file that I'm using along with the newer version of Unity, and I think that the newer version of entities doesn't include the math library that has more features? Still seems weird that the math stuff isn't split up in it's own package.

[manifest.zip](https://github.com/Necromantic/ECS-Sandbox/files/2217509/manifest.zip)

**Comment by Necromantic** [comment]
I've just pushed a new commit. It's working with 2018.2 for me now.
It seems they have changed some things around and removed some methods (like math.scale that was used) from the math namespace and made it methods of the matrices themselves.

**Comment by MilanDierick** [comment]
Alright, it works perfectly now.
Thank you for the quick respone :-).
Now I can start implementing my planned mechanics in ECS.

**Comment by Necromantic** [comment]
You're welcome.
The things I do at 2 in the morning on my holidays. ;)

**Comment by MilanDierick** [comment]
Hehe, it's getting 3 a.m. here, and I'm on holidays as well, best time of the year :-D
